replicaCount: 2

image:
  repository: 236604669997.dkr.ecr.us-east-1.amazonaws.com/roman
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

containerPort: 80
